name: Publish Image

on:
  push:
    tags:
      - "*"

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: |
          echo TAG_NAME=$(echo $GITHUB_REF | sed -e "s|refs/tags/||") >> $GITHUB_ENV
      - name: Build and push collector image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./package/collector/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/rancher-sandbox/profiling-collector:${{ env.TAG_NAME }}
      - name : Build and push chaos tool image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./package/chaos-tool/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/rancher-sandbox/profiling-chaos-tool:${{ env.TAG_NAME }}
